apiVersion: v1
kind: Secret
metadata:
  name: oficina-secret
  namespace: oficina
type: Opaque
stringData:
  ConnectionStrings__SqlServer: "Server=sqlserver,1433;Database=OficinaDb;User Id=sa;Password=Oficina_dev_2026!;TrustServerCertificate=True;"
  MSSQL_SA_PASSWORD: "Oficina_dev_2026!"
  Jwt__Secret: "oficina-local-development-secret-2026"
  Jwt__Key: "oficina-local-development-secret-2026"
  AdminInicial__Cpf: "39053344705"
  AdminInicial__Senha: "Senha@123"
