apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: oficina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oficina-secret
                  key: MSSQL_SA_PASSWORD
          volumeMounts:
            - name: sqlserver-data
              mountPath: /var/opt/mssql
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
      volumes:
        - name: sqlserver-data
          emptyDir: {}
