apiVersion: v1
kind: Secret
metadata:
  name: oficina-secret
type: Opaque
stringData:
  CONNECTION_STRING: "Server=sqlserver,1433;Database=OficinaDb;User Id=sa;Password=Your_password123!;TrustServerCertificate=True;"
