services:
  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      - "5001:80"
      - "2525:25"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_DPASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S sqlserver -U ${MSSQL_USER} -P ${MSSQL_DPASSWORD} -Q 'SELECT 1' -C || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 20

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Docker"
      ConnectionStrings__SqlServer: >
        Server=sqlserver,${PORT_SQLSERVER};
        Database=${MSSQL_DATABASE};
        User Id=${MSSQL_USER};
        Password=${MSSQL_DPASSWORD};
        TrustServerCertificate=True;
      Jwt__Key: ${JWT_KEY} 
      Jwt__Issuer: ${NOME_API} 
      Jwt__Audience: ${NOME_API}
      Jwt__ExpMinutes: "120"
      EmailSettings__SmtpHost: "smtp4dev"
      EmailSettings__SmtpPort: "25"
      EmailSettings__EnableSsl: "false"
      EmailSettings__From: "no-reply@oficina.local"
      EmailSettings__BaseUrl: "http://localhost:8080"
    ports:
      - "8080:8080"
    depends_on:
      smtp4dev:
        condition: service_started
      sqlserver:
        condition: service_healthy

volumes:
  sqlserverdata:
