name: Workflow - OficinaApi

on: 
  push:
    branches: [main, developer, feat/jaque]

jobs:
  build-deploy:
    name: Build, Push e Deploy
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Docker login
      - name: Docker Login
        uses: docker/login-action@v4
        with:
          username: jaquelineramosit
          password: ${{ secrets.DOCKERHUB_PA_SECRET }}

      # 3️⃣ Build e push Docker
      - name: Build and Push Docker
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./docker/Dockerfile
          tags: |
            jaquelineramosit/oficina-api:latest
            jaquelineramosit/oficina-api:${{ github.sha }}
          push: true

      # 4️⃣ Configura AWS
      - name: AWS Credentials (temporárias)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 5️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # 6️⃣ Terraform Apply EKS
      - name: Terraform Init EKS
        run: terraform init ./terraform/eks

      - name: Terraform Apply EKS
        run: terraform apply -auto-approve ./terraform/eks

      # 7️⃣ Configura kubeconfig
      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name oficina-cluster

      # 8️⃣ Terraform Apply Kubernetes (com tag dinâmica)
      - name: Terraform Init Kubernetes
        run: terraform init ./terraform/kubernetes

      - name: Terraform Apply Kubernetes
        run: terraform apply -auto-approve \
              -var="docker_image_tag=${{ github.sha }}" \
              -var="docker_image_repo=jaquelineramosit/oficina-api" \
              ./terraform/kubernetes